name: fluttertrans
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/ShivanshuKGupta/fluttertrans

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  cli_spin: ^1.0.1
  translator: ^1.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
