name: fluttertrans
description: Command-line tool for translation of strings in Flutter applications at compile time
version: 0.0.4
repository: https://github.com/ShivanshuKGupta/fluttertrans

environment:
  sdk: ^3.4.3

dependencies:
  cli_spin: ^1.0.1
  translator: ^1.0.0
  analyzer: ^6.5.0

executables:
  fluttertrans: fluttertrans

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
